# Generated by Django 4.2.2 on 2023-07-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_alter_personajuridica_representante_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradora',
            },
        ),
        migrations.CreateModel(
            name='Contratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
            ],
            options={
                'verbose_name': 'Contratante',
                'verbose_name_plural': 'Contratante',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ramo',
                'verbose_name_plural': 'Ramo',
            },
        ),
        migrations.CreateModel(
            name='SubRamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.ramo')),
            ],
            options={
                'verbose_name': 'Sub Ramo',
                'verbose_name_plural': 'Sub Ramo',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('Ejecutivo', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Colectiva', 'Colectiva'), ('Oficio', 'Oficio')], max_length=100, null=True)),
                ('concepto', models.CharField(choices=[('Nueva póliza', 'Nueva póliza'), ('Renovación', 'Renovación')], max_length=100, null=True)),
                ('cesionario', models.BooleanField()),
                ('aseguradora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.aseguradora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.cliente')),
                ('contratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.contratante')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.grupo')),
                ('ramo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.ramo')),
                ('subramo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.subramo')),
            ],
            options={
                'verbose_name': 'Poliza',
                'verbose_name_plural': 'Poliza',
            },
        ),
    ]
