# Generated by Django 4.2.2 on 2023-07-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poliza',
            old_name='Ejecutivo',
            new_name='ejecutivo',
        ),
    ]
