# Generated by Django 4.2.2 on 2023-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_rename_ejecutivo_poliza_ejecutivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subramo',
            old_name='departamento',
            new_name='Ramo',
        ),
        migrations.AlterField(
            model_name='poliza',
            name='cliente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='contratante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Contratante',
        ),
    ]
