# Generated by Django 4.2.2 on 2023-06-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(max_length=100, null=True)),
                ('estadoCivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Union Libre')], max_length=100, null=True)),
                ('identificacion', models.CharField(choices=[('Cédula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('RUC', 'RUC')], max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.departamento')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.empresa')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.municipio')),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Persona Natural',
            },
        ),
    ]
