# Generated by Django 4.2.2 on 2023-07-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanatural',
            name='estadoCivil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('ruc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('actividadEconomica', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('web', models.CharField(max_length=100, null=True)),
                ('cesionario', models.BooleanField()),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.departamento')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.municipio')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.personanatural')),
            ],
            options={
                'verbose_name': 'Persona Juridica',
                'verbose_name_plural': 'Persona Juridica',
            },
        ),
    ]
