# Generated by Django 4.2.2 on 2023-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_personanatural_estadocivil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personanatural',
            old_name='nombre',
            new_name='primer_apellido',
        ),
        migrations.AddField(
            model_name='personanatural',
            name='primer_nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='segundo_apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='segundo_nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
