# Generated by Django 4.2.2 on 2023-07-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_nombre_personanatural_primer_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personanatural',
            old_name='primer_apellido',
            new_name='primerApellido',
        ),
        migrations.RenameField(
            model_name='personanatural',
            old_name='primer_nombre',
            new_name='primerNombre',
        ),
        migrations.RenameField(
            model_name='personanatural',
            old_name='segundo_apellido',
            new_name='segundoApellido',
        ),
        migrations.RenameField(
            model_name='personanatural',
            old_name='segundo_nombre',
            new_name='segundoNombre',
        ),
    ]
