# Generated by Django 4.2.2 on 2023-07-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_primer_apellido_personanatural_primerapellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.personanatural'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaJuridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.personajuridica')),
                ('personaNatural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.personanatural')),
            ],
        ),
    ]
