# Generated by Django 4.2.2 on 2023-07-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_personanatural_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'documentacion',
                'verbose_name_plural': 'documentacion',
            },
        ),
        migrations.RemoveField(
            model_name='personajuridica',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='personanatural',
            name='documento',
        ),
    ]
