# Generated by Django 4.2.2 on 2023-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_documento_remove_personajuridica_documento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='documentacion',
        ),
        migrations.AddField(
            model_name='personajuridica',
            name='documento',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personanatural',
            name='documento',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
