# Generated by Django 4.2.2 on 2023-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_delete_documento_personajuridica_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personanatural',
            name='documento',
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='documento',
            field=models.FileField(upload_to='document/persona_juridica'),
        ),
    ]
