# Generated by Django 4.2.2 on 2023-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_personanatural_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='documento',
            field=models.FileField(null=True, upload_to='persona_juridica'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='documento',
            field=models.FileField(null=True, upload_to='persona_natural'),
        ),
    ]
