# Generated by Django 4.2.2 on 2023-08-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0003_rename_departamento_subramo_ramo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('formaPago', models.CharField(choices=[('Contado', 'Contado'), ('Fraccionado', 'Fraccionado')], max_length=100, null=True)),
                ('pagoPor', models.CharField(choices=[('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Deposito', 'Deposito'), ('Tarjeta De Crédito', 'Tarjeta De Crédito'), ('Deducción Por Nomina', 'Deducción Por Nomina'), ('Efectivo', 'Efectivo')], max_length=100, null=True)),
                ('cantidadCuotas', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prima', models.FloatField()),
                ('descuento', models.FloatField()),
                ('emision', models.FloatField()),
                ('iva', models.FloatField()),
                ('otrosGastos', models.FloatField()),
                ('comision', models.FloatField()),
                ('porcentajeSubComision', models.FloatField()),
                ('MontoComision', models.FloatField()),
                ('moneda', models.CharField(choices=[('Cordoba', 'Cordoba'), ('Euro', 'Euro'), ('Dolar', 'Dolar')], max_length=100, null=True)),
                ('poliza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.poliza')),
            ],
        ),
    ]
