# Generated by Django 4.2.2 on 2023-08-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='MontoComision',
            new_name='montoComision',
        ),
    ]
