# Generated by Django 4.2.2 on 2023-08-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_montocomision_recibo_montocomision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='id',
            new_name='recibo',
        ),
    ]
