# Generated by Django 4.2.2 on 2023-08-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_rename_departamento_subramo_ramo_and_more'),
        ('payment', '0003_rename_id_recibo_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='primaNeta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='comision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='descuento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='emision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='iva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='montoComision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='otrosGastos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='porcentajeSubComision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='prima',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.FloatField()),
                ('saldo', models.FloatField()),
                ('comision', models.FloatField()),
                ('estado', models.CharField(default='Pendiente', max_length=100)),
                ('dias_mora', models.IntegerField(default=0)),
                ('poliza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.poliza')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.recibo')),
            ],
        ),
    ]
